#!/bin/sh

# Wait for the Wireplumber media session daemon to start.
sv check "$HOME/.runit/sv/wireplumber" >/dev/null || exit 1

[ -r ./conf ] && . ./conf

if [ "${LOGGING_ENABLE}x" = "1x" -a -n "${LOG_LEVEL}" ]; then
    export PIPEWIRE_DEBUG="${LOG_LEVEL}"
fi

exec pipewire-pulse ${OPTS:-} 2>&1
